# Generated by Django 5.1.1 on 2024-09-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitModel',
            fields=[
                ('nrCpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], max_length=8)),
                ('points', models.IntegerField()),
            ],
            options={
                'db_table': 'customer_benefits',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
